name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@ba338faac060b1f62598fb2aea122db3926aad6e # v2.0.18
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
