name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: false

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
    uses: USA-RedDragon/reusable-actions/.github/workflows/goreleaser.yaml@f2c111fa5bc57400edd87fdde50b1953c721d400 # v2.0.14
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
